-- Workspace ownership transfer.
--
-- owner_email / workspace_owner_email is part of the primary key (or a
-- unique-constrained foreign key) on several tables. Postgres foreign key
-- constraints are NOT deferrable by default, so a same-transaction,
-- multi-table rename of an owner_email value would fail on the first
-- statement that temporarily makes a child row point at a not-yet-updated
-- (or already-updated) parent row. Step 1 makes the relevant composite FK
-- constraints deferrable so `transfer_workspace_ownership` can defer all
-- constraint checks to commit time.

-- 1) Make composite FKs referencing inbox_conversations(owner_email, id)
--    deferrable. Constraint names were auto-generated by Postgres (never
--    specified explicitly), so we look them up dynamically instead of
--    guessing.
do $$
declare
  r record;
begin
  for r in
    select conname, conrelid::regclass::text as tbl
    from pg_constraint
    where contype = 'f'
      and confrelid = 'public.inbox_conversations'::regclass
      and conrelid in (
        'public.inbox_messages'::regclass,
        'public.inbox_call_events'::regclass,
        'public.inbox_calendly_invites'::regclass
      )
  loop
    execute format(
      'alter table %s alter constraint %I deferrable initially deferred',
      r.tbl,
      r.conname
    );
  end loop;
end $$;

-- 2) Atomic ownership transfer.
--
-- Moves a workspace (all owner-scoped data) from the current owner to an
-- existing team member of that owner. The previous owner becomes a regular
-- team member (setter/closer) under the new owner.
--
-- Deliberately excluded: public.instagram_accounts. Instagram connections
-- are keyed by the individual user_email that ran the OAuth flow, not by
-- workspace owner, and carry external OAuth/webhook implications. They are
-- not moved automatically; reconnecting/re-assigning Instagram accounts
-- after a transfer is a separate, explicit action.
create or replace function public.transfer_workspace_ownership(
  p_current_owner_email text,
  p_new_owner_email text,
  p_previous_owner_new_role text default 'closer'
) returns jsonb
language plpgsql
as $$
declare
  v_current_owner text := lower(trim(p_current_owner_email));
  v_new_owner text := lower(trim(p_new_owner_email));
  v_previous_owner_role public.team_member_role;
  v_current_owner_role public.app_user_role;
  v_membership_exists boolean;
  v_conversations_moved int;
  v_messages_moved int;
  v_call_events_moved int;
  v_calendly_invites_moved int;
  v_sync_job_moved int;
  v_team_members_moved int;
  v_status_tags_moved int;
  v_status_tags_skipped int;
  v_calendly_connection_moved int;
  v_calendly_connection_skipped int;
begin
  if v_current_owner = '' or v_new_owner = '' then
    raise exception 'Current owner and new owner emails are required';
  end if;

  if v_current_owner = v_new_owner then
    raise exception 'New owner must be different from the current owner';
  end if;

  if p_previous_owner_new_role not in ('setter', 'closer') then
    raise exception 'previous_owner_new_role must be ''setter'' or ''closer''';
  end if;
  v_previous_owner_role := p_previous_owner_new_role::public.team_member_role;

  select role into v_current_owner_role
  from public.app_users
  where email = v_current_owner
  for update;

  if v_current_owner_role is null then
    raise exception 'Current owner % does not exist', v_current_owner;
  end if;

  if v_current_owner_role <> 'owner' then
    raise exception '% is not the workspace owner', v_current_owner;
  end if;

  if not exists (select 1 from public.app_users where email = v_new_owner for update) then
    raise exception 'New owner % does not exist', v_new_owner;
  end if;

  select exists (
    select 1 from public.team_members
    where owner_email = v_current_owner and member_email = v_new_owner
  ) into v_membership_exists;

  if not v_membership_exists then
    raise exception '% must already be a team member of % to receive ownership', v_new_owner, v_current_owner;
  end if;

  -- Defer FK checks made deferrable above to transaction commit time, so the
  -- bulk updates below can run in any order without tripping over each other.
  set constraints all deferred;

  -- app_users: repoint every other team member's team_owner_email pointer
  -- first, then flip the two swapping accounts explicitly.
  update public.app_users
    set team_owner_email = v_new_owner, updated_at = now()
    where team_owner_email = v_current_owner
      and email <> v_new_owner;

  update public.app_users
    set role = 'owner', team_owner_email = null, updated_at = now()
    where email = v_new_owner;

  update public.app_users
    set role = v_previous_owner_role, team_owner_email = v_new_owner, updated_at = now()
    where email = v_current_owner;

  -- team_members: drop the old owner -> new owner row, move every remaining
  -- team member under the new owner, then add the previous owner back as a
  -- regular member.
  delete from public.team_members
    where owner_email = v_current_owner and member_email = v_new_owner;

  update public.team_members
    set owner_email = v_new_owner, updated_at = now()
    where owner_email = v_current_owner;
  get diagnostics v_team_members_moved = row_count;

  insert into public.team_members (owner_email, member_email, role, added_at, updated_at)
  values (v_new_owner, v_current_owner, v_previous_owner_role, now(), now())
  on conflict (owner_email, member_email)
  do update set role = excluded.role, updated_at = now();

  -- Owner-scoped inbox data.
  update public.inbox_conversations
    set owner_email = v_new_owner, updated_at = now()
    where owner_email = v_current_owner;
  get diagnostics v_conversations_moved = row_count;

  update public.inbox_messages
    set owner_email = v_new_owner, updated_at = now()
    where owner_email = v_current_owner;
  get diagnostics v_messages_moved = row_count;

  update public.inbox_call_events
    set owner_email = v_new_owner, updated_at = now()
    where owner_email = v_current_owner;
  get diagnostics v_call_events_moved = row_count;

  update public.inbox_calendly_invites
    set owner_email = v_new_owner, updated_at = now()
    where owner_email = v_current_owner;
  get diagnostics v_calendly_invites_moved = row_count;

  -- inbox_sync_jobs is keyed solely by owner_email (primary key). The new
  -- owner should never already have one (they weren't an owner before), but
  -- guard defensively rather than erroring the whole transfer.
  delete from public.inbox_sync_jobs where owner_email = v_new_owner;
  update public.inbox_sync_jobs
    set owner_email = v_new_owner, updated_at = now()
    where owner_email = v_current_owner;
  get diagnostics v_sync_job_moved = row_count;

  -- workspace_status_tags: unique on (workspace_owner_email, normalized_name).
  -- Skip any row that would collide with a tag the new owner already has
  -- (e.g. leftover from a prior ownership) instead of failing the transfer;
  -- skipped rows stay attributed to the previous owner for manual review.
  update public.workspace_status_tags t
    set workspace_owner_email = v_new_owner, updated_at = now()
    where t.workspace_owner_email = v_current_owner
      and not exists (
        select 1 from public.workspace_status_tags e
        where e.workspace_owner_email = v_new_owner
          and e.normalized_name = t.normalized_name
      );
  get diagnostics v_status_tags_moved = row_count;

  select count(*) into v_status_tags_skipped
  from public.workspace_status_tags
  where workspace_owner_email = v_current_owner;

  -- workspace_calendly_connections: unique on (workspace_owner_email). Skip
  -- if the new owner already has a connection of their own.
  update public.workspace_calendly_connections c
    set workspace_owner_email = v_new_owner, updated_at = now()
    where c.workspace_owner_email = v_current_owner
      and not exists (
        select 1 from public.workspace_calendly_connections e
        where e.workspace_owner_email = v_new_owner
      );
  get diagnostics v_calendly_connection_moved = row_count;

  select count(*) into v_calendly_connection_skipped
  from public.workspace_calendly_connections
  where workspace_owner_email = v_current_owner;

  return jsonb_build_object(
    'previous_owner_email', v_current_owner,
    'new_owner_email', v_new_owner,
    'previous_owner_new_role', v_previous_owner_role,
    'team_members_moved', v_team_members_moved,
    'conversations_moved', v_conversations_moved,
    'messages_moved', v_messages_moved,
    'call_events_moved', v_call_events_moved,
    'calendly_invites_moved', v_calendly_invites_moved,
    'sync_job_moved', v_sync_job_moved,
    'status_tags_moved', v_status_tags_moved,
    'status_tags_skipped', v_status_tags_skipped,
    'calendly_connection_moved', v_calendly_connection_moved,
    'calendly_connection_skipped', v_calendly_connection_skipped,
    'instagram_accounts_moved', 0
  );
end;
$$;

-- Server-only, same convention as append_setter_ai_exchange in
-- 060_rpc_functions.sql: no explicit SECURITY DEFINER, callable only via the
-- service-role Supabase client which already bypasses RLS.
revoke execute on function public.transfer_workspace_ownership(text, text, text) from public, anon, authenticated;
grant execute on function public.transfer_workspace_ownership(text, text, text) to service_role;
