export default function SummaryTab() {
  return (
    <div className="flex-1 overflow-y-auto p-6 bg-white">
      {/* Info Header */}
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center">
          <img src="/icons/Info.svg" alt="Info" className="w-6 h-5 mr-2" />
          <p className="text-xs text-gray-500 font-medium">Summary is generated by using info in this chat.</p>
        </div>
        <button className="ml-2 text-[10px] font-bold bg-[#9ca3af] text-white px-3 py-1 rounded-full">Summarize</button>
      </div>

      {/* Summary Card */}
      <div className="bg-white rounded-xl border border-gray-200 p-5 shadow-sm text-xs leading-relaxed">
        <p className="font-bold text-gray-900 text-sm mb-3">Client Snapshot</p>

        <ul className="space-y-3 pl-1 text-gray-600">
          <li className="flex items-start">
            <span className="mr-2 text-gray-300 text-[8px] mt-1.5">●</span>
            <span>
              <span className="font-bold text-gray-800">Profile:</span> 5'6", 168 lbs | Goal: 145–150 lbs (strong, toned)
            </span>
          </li>
          <li className="flex items-start">
            <span className="mr-2 text-gray-300 text-[8px] mt-1.5">●</span>
            <span>
              <span className="font-bold text-gray-800">Pain Points:</span> Last 15 lbs post-baby | Inconsistent workouts (work + toddler chaos) | Overwhelmed by
              generic plans | Low confidence (skips photos/beach)
            </span>
          </li>
          <li className="flex items-start">
            <span className="mr-2 text-gray-300 text-[8px] mt-1.5">●</span>
            <span>
              <span className="font-bold text-gray-800">Availability:</span> 30–45 min sessions, 4×/week evenings
            </span>
          </li>
          <li className="flex items-start">
            <span className="mr-2 text-gray-300 text-[8px] mt-1.5">●</span>
            <span>
              <span className="font-bold text-gray-800">Budget:</span> $300–450/mo
            </span>
          </li>
          <li className="flex items-start">
            <span className="mr-2 text-gray-300 text-[8px] mt-1.5">●</span>
            <span>
              <span className="font-bold text-gray-800">Big Motivator:</span> June Mexico anniversary trip — wants bikini-ready
            </span>
          </li>
          <li className="flex items-start">
            <span className="mr-2 text-gray-300 text-[8px] mt-1.5">●</span>
            <span>
              <span className="font-bold text-gray-800">Preferences:</span> Loves custom macros + weekly accountability
            </span>
          </li>
          <li className="flex items-start">
            <span className="mr-2 text-gray-300 text-[8px] mt-1.5">●</span>
            <span>
              <span className="font-bold text-gray-800">Open to:</span> 12-week 1:1 coaching
            </span>
          </li>
        </ul>

        <div className="my-5" />

        <p className="font-bold text-gray-900 text-sm mb-3">Action Plan</p>
        <ul className="space-y-3 pl-1 text-gray-600">
          <li className="flex items-start">
            <span className="mr-2 text-gray-300 text-[8px] mt-1.5">●</span>
            <span>Send proposal tonight: 12-week program @ $349/mo (custom workouts/nutrition, unlimited DMs)</span>
          </li>
          <li className="flex items-start">
            <span className="mr-2 text-gray-300 text-[8px] mt-1.5">●</span>
            <span>Follow up tomorrow evening (voice call or DM) to close</span>
          </li>
          <li className="flex items-start">
            <span className="mr-2 text-gray-300 text-[8px] mt-1.5">●</span>
            <span>
              <span className="font-bold text-gray-800">Goal:</span> Onboard by end of week
            </span>
          </li>
        </ul>
      </div>
    </div>
  );
}